language: scala
scala:
  - 2.12.8
  - 2.11.12

env:
  global:
    - AKKA_TEST_TIMEFACTOR=2.0

sudo: required

services:
  - docker

before_install:
  - docker pull eventstore/eventstore
  - docker run -d --rm --name eventstore-node -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_START_STANDARD_PROJECTIONS=True eventstore/eventstore

script:
  - sbt ++$TRAVIS_SCALA_VERSION test it:test

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm