
jdk:
  - openjdk8

language: scala

scala:
  - 2.13.7
  - 2.12.15

sudo: required

services:
  - docker

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile it:compile test

jobs:
  include:
    - stage: integration-5x
      scala: 2.13.8
      env: AKKA_TEST_TIMEFACTOR=2.0 AKKA_TEST_LOGLEVEL=OFF
      before_install:
        - docker pull eventstore/eventstore:release-5.0.11
        - docker run -d --rm --name eventstore-node -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_MEM_DB=True -e EVENTSTORE_WRITE_STATS_TO_DB=False -e EVENTSTORE_START_STANDARD_PROJECTIONS=True eventstore/eventstore:release-5.0.11
      script:
        - sbt test:compile
        - travis_retry sbt it:test

    - stage: integration-21.x
      scala: 2.13.8
      env: AKKA_TEST_TIMEFACTOR=2.0 AKKA_TEST_LOGLEVEL=OFF
      before_install:
        - docker pull eventstore/eventstore:21.10.0-bionic
        - docker run -d --rm --name eventstore-node-20 -p 2113:2113 -p 1113:1113 -e EVENTSTORE_INSECURE=True -e EVENTSTORE_MEM_DB=True -e EVENTSTORE_ENABLE_EXTERNAL_TCP=True -e EVENTSTORE_START_STANDARD_PROJECTIONS=True -e EVENTSTORE_RUN_PROJECTIONS=System eventstore/eventstore:21.10.0-bionic
      script:
        - sbt test:compile
        - travis_retry sbt it:test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm