jdk:
  - openjdk8

language: scala

scala:
  - 2.13.1
  - 2.12.10

sudo: required

services:
  - docker

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile it:compile test

jobs:
  include:
    - stage: integration
      scala: 2.13.1
      env: AKKA_TEST_TIMEFACTOR=2.0 AKKA_TEST_LOGLEVEL=OFF
      before_install:
        - docker pull eventstore/eventstore:release-5.0.5
        - docker run -d --rm --name eventstore-node -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_MEM_DB=True -e EVENTSTORE_STATS_PERIOD_SEC=1200 -e EVENTSTORE_START_STANDARD_PROJECTIONS=True eventstore/eventstore:release-5.0.5
      script:
        - sbt test:compile
        - travis_retry sbt it:test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm