version: '3.8'
services:

  esdb:
    image: eventstore/eventstore:21.10.0-bionic
    environment:
      - EVENTSTORE_MEM_DB=True
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=True
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_RUN_PROJECTIONS=System
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
    ports:
      - 2113:2113
      - 1113:1113
    networks:
      esdb_20_network:
        ipv4_address: 172.21.0.2

networks:
  esdb_20_network:
    name: esdb-20-net
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16